services:
  web:
    build: 
          dockerfile: node.Dockerfile
          context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
